# Generated by Django 5.0.7 on 2024-08-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_listing_is_close"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to="static/auctions/image"),
        ),
    ]
