# Generated by Django 5.0.7 on 2024-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="auctions/static/auctions/image"
            ),
        ),
    ]
