# Generated by Django 5.0.7 on 2024-08-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to="image"),
        ),
    ]
